name: create vnet

on: 
  workflow_call:
    inputs:
      templateFile:
        required: true
        type: string
      parameterFile:
        required: true
        type: string
      subId:
        required: true
        type: string
      rgroup:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: 'inital test 2'
        run: | 
          echo "inputs: ${{ inputs.params }}"

      - name: 'login az cli'
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: 'Run a cli command'
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      
      - name: Replace envsubst styled tokens
        uses: jonlabelle/replace-tokens-action@v1
        with:
          paths: ${{inputs.parameterFile}}
        env:
          VMPASS: ${{secrets.VMPASS}}
    
      - name: Run Bicep deploy
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          subscription-id: ${{ inputs.subId }}
          resource-group-name: ${{ inputs.rgroup }}
          template-file: ${{ inputs.templateFile }}
          parameters-file: ${{ inputs.parameterFile }}
          operation: create
          scope: resourceGroup
          
